on: push
name: Docker Build and Push
jobs:
  dockerLogin:
    name: Docker Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: zcong/istio-grpc-demo-ts
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
